version: '3'
services:
    web:
        build:
            context: .
            args:
                GITHUB_TOKEN: ${GITHUB_TOKEN}
        ports:
            - "6006:6006"
        volumes:
            - .:/app
            - /app/node_modules
        command: yarn storybook
