version: '3'
services:
    web:
        build:
            context: .
            args:
                NODE_AUTH_TOKEN: ${NODE_AUTH_TOKEN}
        ports:
            - "6006:6006"
        volumes:
            - .:/app
            - /app/node_modules
        command: npm run storybook
