version: '3'
services:
    web:
        build: .
        ports:
            - "6006:6006"
        volumes:
            - .:/app
            - /app/node_modules
        command: [ "yarn", "storybook", "--no-manager-cache" ]
