name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com' # GitHub Package Registry URL

      - name: Install dependencies
        run: yarn install

      - name: ESLint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build package
        run: yarn build

      - name: Bump version and create a release commit
        id: package_version
        run: |
          git checkout .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version patch -m "chore(release): %s [skip ci]"
          git push origin main
          echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.package_version.outputs.version }}
          release_name: Release ${{ steps.package_version.outputs.version }}
          body: 'https://www.npmjs.com/package/react-vrw/v/${{ steps.package_version.outputs.version }}'
          draft: false
          prerelease: false

      - name: Build Storybook
        run: yarn build-storybook
        if: github.ref == 'refs/heads/main'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages # デプロイ先のブランチ
          folder: storybook-static # Storybookのビルドディレクトリ
